### ISSUE TITLE
Fix Function Use CountryCodesQuery

### ISSUE THREAD

**Issue by Pauldro** [cptechinc/dplus-model#3]
The filterById($country_code) function needs to be updated
The function itself is doing a findOneXXX() type of function when the function itself is named filterByXXX() 
To remedy this, you can just use findOneById() then call the description property from that.  

https://github.com/cptechinc/dplus-model/blob/97f98bf93f18973904a6e10cf49c8536a3d606d8/src/Model/CountryCodesQuery.php#L19-L22

**Comment by bbullemer** [comment]
The above commit was supposed to be for #4, not #3 commit: bf359e1
